/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.sis.util.iso;

import java.util.Map;
import java.util.Set;
import org.opengis.util.Type;
import org.opengis.util.TypeName;
import org.opengis.util.MemberName;
import org.opengis.util.Record;
import org.opengis.util.RecordType;
import org.opengis.util.RecordSchema;


/**
 * Auto-generated by NetBeans.
 */
public class DefaultRecordType implements RecordType {

    @Override
    public TypeName getTypeName() {
        throw new UnsupportedOperationException();
    }

    @Override
    public RecordSchema getContainer() {
        throw new UnsupportedOperationException();
    }

    @Override
    public Map<MemberName, Type> getMemberTypes() {
        throw new UnsupportedOperationException();
    }

    @Override
    public Set<MemberName> getMembers() {
        throw new UnsupportedOperationException();
    }

    @Override
    public TypeName locate(MemberName mn) {
        throw new UnsupportedOperationException();
    }

    @Override
    public boolean isInstance(Record record) {
        throw new UnsupportedOperationException();
    }
}
