/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.sis.resources.embedded;

import java.util.ArrayList;
import java.util.Set;
import java.util.Locale;
import java.util.StringJoiner;
import java.util.logging.Logger;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import javax.sql.DataSource;
import org.hsqldb.jdbc.JDBCDataSource;
import org.apache.sis.util.Workaround;
import org.apache.sis.util.internal.shared.MetadataServices;
import org.apache.sis.metadata.sql.internal.shared.Initializer;
import org.apache.sis.setup.InstallationResources;
import org.apache.sis.system.DataDirectory;
import org.apache.sis.util.logging.Logging;
import org.apache.sis.util.resources.Errors;


/**
 * Provides an embedded database for the <abbr>EPSG</abbr> geodetic dataset and other resources.
 * Provides also a copy of the <a href="https://epsg.org/terms-of-use.html">EPSG terms of use</a>,
 * which should be accepted by users before the EPSG dataset can be installed.
 *
 * @author  Martin Desruisseaux (Geomatys)
 * @version 1.7
 * @since   0.8
 *
 * @see <a href="https://epsg.org/">https://epsg.org/</a>
 */
public class EmbeddedResources extends InstallationResources {
    /**
     * The root directory of data embedded in the <abbr>JAR</abbr> file.
     * It must be an invalid package name, because otherwise the Java Module System enforces
     * encapsulation in the same way as non-exported packages, which makes files inaccessible.
     * This naming trick is part of Java Module specification, so it should be reliable.
     */
    static final String DIRECTORY = "SIS-DATA";

    /**
     * The directory of embedded databases.
     * This is a sub-directory of {@link #DIRECTORY}.
     */
    static final String DATABASES = "Databases";

    /**
     * Suffixes of all files generated by HSQLDB in the database directory.
     */
    static String[] databaseSuffixes() {
        return new String[] {"properties", "script", "data"};
    }

    /**
     * Whether to copy the HSQLDB files to a temporary directory.
     * This is a workaround for HSQLDB slowness as embedded database.
     *
     * @see <a href="https://sourceforge.net/p/hsqldb/bugs/1758/">HSQLDB issue 1758</a>
     */
    @Workaround(library = "HSQLDB", version = "2.7.4")
    private static final boolean COPY_TO_TMP = true;

    /**
     * The data source, created when first needed.
     * Also set to a different value during tests.
     */
    static DataSource dataSource;

    /**
     * Creates a new provider for connections to the embedded database.
     */
    public EmbeddedResources() {
    }

    /**
     * Returns the pseudo-authority, which is {@code "Embedded"}.
     *
     * @return {@code "Embedded"} pseudo-authority.
     */
    @Override
    public Set<String> getAuthorities() {
        return Set.of(MetadataServices.EMBEDDED);
    }

    /**
     * Verifies that the given authority is the expected values.
     */
    private void verifyAuthority(final String authority) {
        if (!MetadataServices.EMBEDDED.equalsIgnoreCase(authority)) {
            throw new IllegalArgumentException(Errors.format(Errors.Keys.IllegalArgumentValue_2, "authority", authority));
        }
    }

    /**
     * Returns the license of embedded data.
     *
     * @param  authority  shall be {@code "Embedded"}.
     * @param  locale     the preferred locale for the terms of use.
     * @param  mimeType   either {@code "text/plain"} or {@code "text/html"}.
     * @return the terms of use in plain text or HTML, or {@code null} if none.
     * @throws IllegalArgumentException if the given {@code authority} argument is not the expected values.
     * @throws IOException if an error occurred while reading the license file.
     */
    @Override
    public String getLicense(String authority, Locale locale, String mimeType) throws IOException {
        verifyAuthority(authority);
        final String filename;
        if ("text/plain".equalsIgnoreCase(mimeType)) {
            filename = "LICENSE.txt";
        } else if ("text/html".equalsIgnoreCase(mimeType)) {
            filename = "LICENSE.html";
        } else {
            return null;
        }
        final var buffer = new StringJoiner(System.lineSeparator(), "", System.lineSeparator());
        try (BufferedReader in = new BufferedReader(new InputStreamReader(
                EmbeddedResources.class.getResourceAsStream(filename), "UTF-8")))
        {
            String line;
            while ((line = in.readLine()) != null) {
                buffer.add(line);
            }
        }
        return buffer.toString();
    }

    /**
     * Returns the data source name, which is {@code "SpatialMetadata"}.
     *
     * @param  authority  shall be {@code "Embedded"}.
     * @return {@code "SpatialMetadata"}.
     */
    @Override
    public String[] getResourceNames(String authority) {
        verifyAuthority(authority);
        return new String[] {Initializer.DATABASE};
    }

    /**
     * Returns the data source for embedded database.
     * If the {@code SIS_DATA} environment variable is defined and does not contain {@code SpatialMetadata} files,
     * the embedded data will be copied in that directory and the returned {@code DataSource} will use these files.
     * This copy is done because database operations are faster on ordinary files compared to entries embedded in a
     * <abbr>JAR</abbr> file.
     *
     * @param  authority  shall be {@code "Embedded"}.
     * @param  index      shall be 0.
     * @return the embedded data source, or {@code null} if not available.
     */
    @Override
    public DataSource getResource(String authority, int index) {
        verifyAuthority(authority);
        synchronized (Initializer.class) {
            /*
             * Check for `LICENSE.txt` as a way to detect whether the data are available.
             * It should always be the case when using a released JAR file, but it may not
             * be the case when using a local build.
             */
            if (dataSource == null && EmbeddedResources.class.getResourceAsStream("LICENSE.txt") != null) {
                if (!tryInstall(DataDirectory.DATABASES.getDirectory(), false)) {
                    if (COPY_TO_TMP) try {
                        if (tryInstall(Files.createTempDirectory(DATABASES), true)) {
                            return dataSource;
                        }
                    } catch (IOException e) {
                        Logging.recoverableException(
                                Logger.getLogger("org.apache.sis.referencing.database"),
                                EmbeddedResources.class, "getResource", e);
                    }
                    createDataSource("jdbc:hsqldb:res:" + DIRECTORY + '/' + DATABASES + '/' + Initializer.DATABASE);
                }
            }
            return dataSource;
        }
    }

    /**
     * Creates the data source.
     *
     * @param  path  path to the database, starting with the {@code "jdbc:hsqldb:"} prefix.
     */
    private static void createDataSource(final String path) {
        final var ds = new JDBCDataSource();
        ds.setDatabaseName(Initializer.DATABASE);
        ds.setURL(path);
        dataSource = ds;
    }

    /**
     * Unconditionally throws an exception since the embedded database is not provided as <abbr>SQL</abbr> scripts.
     *
     * @param  authority  shall be {@code "Embedded"}.
     * @param  resource   shall be 0.
     * @return never return.
     * @throws IOException always thrown.
     */
    @Override
    public BufferedReader openScript(String authority, int resource) throws IOException {
        verifyAuthority(authority);
        throw new IOException(Errors.format(Errors.Keys.CanNotConvertFromType_2, DataSource.class, BufferedReader.class));
    }

    /**
     * Copies the database files in the given directory if not already present.
     *
     * @param  directory     the directory where to copy database files.
     * @param  deleteOnExit  whether to delete the file when the JVM exit.
     * @return whether the data have been copied as a data source created.
     */
    @SuppressWarnings("UseSpecificCatch")
    private static boolean tryInstall(final Path directory, final boolean deleteOnExit) {
        if (directory != null) try {
            final boolean exists;
            try (DirectoryStream<Path> content = Files.newDirectoryStream(directory,
                    (file) -> file.getFileName().toString().startsWith(Initializer.DATABASE)))
            {
                exists = content.iterator().hasNext();
            }
            if (!exists) {
                final ClassLoader loader = EmbeddedResources.class.getClassLoader();
                final var delete = new ArrayList<Path>(4);
                try {
                    // The array shall contain the suffix of all files generated by HSQLDB.
                    for (final String suffix : databaseSuffixes()) {
                        final String name = Initializer.DATABASE + '.' + suffix;
                        final String path = DIRECTORY + '/' + DATABASES + '/' + name;
                        try (InputStream in = loader.getResourceAsStream(path)) {
                            if (in == null) {
                                throw new FileNotFoundException(path);
                            }
                            final Path target = directory.resolve(name);
                            try (OutputStream out = Files.newOutputStream(target, StandardOpenOption.CREATE_NEW)) {
                                delete.add(target);     // File have been created, delete on failure.
                                in.transferTo(out);
                            }
                        }
                    }
                } catch (Throwable ex) {
                    for (Path path : delete) try {
                        Files.delete(path);
                    } catch (IOException e) {
                        ex.addSuppressed(e);
                    }
                    throw ex;
                }
                if (COPY_TO_TMP && deleteOnExit) {  // This parameter is useful only for the workaround.
                    delete.add(0, directory);
                    delete.forEach((path) -> path.toFile().deleteOnExit());
                }
                createDataSource("jdbc:hsqldb:file:" + directory.resolve(Initializer.DATABASE));
                return true;
            }
        } catch (IOException e) {
            Logging.unexpectedException(
                    Logger.getLogger("org.apache.sis.referencing.database"),
                    EmbeddedResources.class, "getResource", e);
        }
        return false;
    }
}
