#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Resources in this file are for "sis-geotiff" usage only and should not be used by any other module.
# For resources shared by all modules in the Apache SIS project, see "org.apache.sis.util.resources" package.
#
BoxLongerThanExpected_1      = The \u2018{0}\u2019 box is longer than expected.
CannotDecodeCRS              = Cannot decode the Coordinate Reference System.
CannotReadBox_1              = Cannot read the \u2018{0}\u2019 box.
DuplicatedBox_1              = The \u2018{0}\u2019 box appears more than once.
EssentialBoxesIgnored_2      = Cannot create the \u201c{0}\u201d resource because the following essential boxes are not handled: {1}.
OptionalBoxesIgnored_2       = The \u201c{0}\u201d resource has been created but the following boxes have been ignored: {1}.
IllegalChildForBox_2         = Container box \u2018{0}\u2019 cannot contain elements of type \u2018{1}\u2019.
ImageReaderNotFound_1        = Cannot find a {0} image reader.
InconsistentBandDataType     = All bands shall be of the same data type.
InvalidBoxSize_1             = Malformed HEIF file because of invalid box size ({0} bytes).
ManyLocationsForResource_1   = Many locations have been found for the \u201c{0}\u201d resource.
MissingCompressedUnit        = Missing unit of compressed data.
NoDataFoundForResource_1     = No data has been found for the \u201c{0}\u201d resource.
NotImageInputStream          = Not an image input stream.
ResourceIsEmpty_1            = The \u201c{0}\u201d resource is empty.
ResourceIsProtected_1        = The \u201c{0}\u201d resource is protected.
StreamOfUnknownLength        = Stream has an unknown length.
UnexpectedConstructionMethod = Unexpected construction method.
UnspecifiedSampleModel       = The sample model of the image is unspecified.
UnsupportedBoxType_1         = The \u2018{0}\u2019 type of box is unsupported.
UnsupportedComponent_1       = The \u2018{0}\u2019 image component type is unsupported.
UnsupportedCompression       = This compression is unsupported.
UnsupportedCompression_1     = The \u2018{0}\u2019 compression is unsupported.
UnsupportedCrsEncoding_1     = The \u2018{0}\u2019 reference system encoding is unsupported.
UnsupportedImageProfile_1    = The \u2018{0}\u2019 image profile is unsupported.
UnsupportedInterleave_1      = The \u2018{0}\u2019 interleave type is unsupported.
UnsupportedSampleModel_1     = Resource \u201c{0}\u201d uses an unsupported image model.
UnsupportedResourceType_2    = Unsupported type \u2018{1}\u2019 for the \u201c{0}\u201d resource.
UnsupportedVersion_2         = Version {1} of the \u2018{0}\u2019 box is unsupported.
