/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.sis.test;

import java.util.Locale;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.BufferedWriter;
import java.io.OutputStreamWriter;
import org.opengis.util.InternationalString;
import org.apache.sis.util.CharSequences;
import org.apache.sis.util.Deprecable;


/**
 * Base class of all classes used to generate HTML pages to be published on
 * the <a href="http://sis.apache.org/">http://sis.apache.org/</a> web site.
 *
 * <p>This class creates files in the current default directory. It is user's responsibility
 * to move the files to the appropriate Apache SIS {@code "content/"} site directory.</p>
 *
 * @author  Martin Desruisseaux (Geomatys)
 * @since   0.6
 * @version 0.6
 * @module
 */
public abstract class HTMLGenerator implements AutoCloseable {
    /**
     * The encoding of the files to generate.
     */
    private static final String ENCODING = "UTF-8";

    /**
     * The language to use for the reports to generate.
     *
     * @see #toLocalizedString(InternationalString)
     */
    protected static final Locale LOCALE = Locale.US;

    /**
     * The number of space to add or remove in the {@linkplain #margin}
     * when new HTML elements are opened or closed.
     */
    private static final int INDENTATION = 2;

    /**
     * Where to write the HTML page.
     */
    private final BufferedWriter out;

    /**
     * The spaces to write in the margin before every new line.
     * The number of spaces will increase by the indentation amount when new elements are opened.
     *
     * @see #INDENTATION
     */
    private String margin = "";

    /**
     * Creates a new instance which will write in the given file.
     * This constructor immediately writes the HTML header up to the {@code <h1>} line, inclusive.
     *
     * @param  filename The name of the file where to write.
     * @param  title The document title and the title to write as {@code <h1>} line.
     * @throws IOException if the file can not be created (e.g. because it already exists).
     */
    protected HTMLGenerator(final String filename, final String title) throws IOException {
        final File file = new File(filename);
        if (file.exists()) {
            throw new IOException("File " + file.getAbsolutePath() + " already exists.");
        }
        out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), ENCODING));
        out.write("<!DOCTYPE html>");
        out.newLine();
        out.write("<!--");
        out.newLine();
        out.write("  This page is automatically generated by the following class in the test directory:");
        out.newLine();
        out.write("  ");
        out.write(getClass().getCanonicalName());
        out.newLine();
        out.write("-->");
        out.newLine();
        open   ("html");
        open   ("head");
        out.write(margin);
        out.write("<meta charset=\"" + ENCODING + "\"/>");
        out.newLine();
        println("title", CharSequences.replace(title, "™", ""));
        open   ("style type=\"text/css\" media=\"all\"");
        println("@import url(\"./reports.css\");");
        close  ("style");
        close  ("head");
        open   ("body");
        println("h1", title);
    }

    /**
     * Escapes the {@code &}, {@code <} and {@code >} characters.
     *
     * @param  text The text to escape, or {@code null}.
     * @return The escaped text, or {@code null} if the given text was null.
     */
    protected static CharSequence escape(CharSequence text) {
        text = CharSequences.replace(text, "&", "&amp;");
        text = CharSequences.replace(text, "<", "&lt;");
        text = CharSequences.replace(text, ">", "&gt;");
        return text;
    }

    /**
     * Opens a new HTML element and increase the indentation.
     *
     * @param  element The HTML element without brackets (e.g. {@code "h2"}).
     * @throws IOException if an error occurred while writing to the file.
     */
    protected final void open(final String element) throws IOException {
        out.write(margin);
        out.write('<');
        out.write(element);
        out.write('>');
        out.newLine();
        margin = CharSequences.spaces(margin.length() + INDENTATION).toString();
    }

    /**
     * Closes a HTML element an opens a new one on the same line.
     *
     * @param  previous The HTML element to close, without brackets.
     * @param  element  The HTML element without brackets (e.g. {@code "h2"}).
     * @throws IOException if an error occurred while writing to the file.
     */
    protected final void reopen(final String previous, final String element) throws IOException {
        out.write(CharSequences.spaces(margin.length() - INDENTATION).toString());
        out.write("</");
        out.write(previous);
        out.write("><");
        out.write(element);
        out.write('>');
        out.newLine();
    }

    /**
     * Closes a HTML element and decrease the indentation. The {@code previous} argument must matches
     * the argument given to the last call to {@link #open(String)}.
     *
     * @param  previous The HTML element without brackets (e.g. {@code "h2"}).
     * @throws IOException if an error occurred while writing to the file.
     */
    protected final void close(final String previous) throws IOException {
        margin = CharSequences.spaces(margin.length() - INDENTATION).toString();
        out.write(margin);
        out.write("</");
        out.write(previous);
        out.write('>');
        out.newLine();
    }

    /**
     * Writes the given text in the given HTML element.
     * {@code &}, {@code <} and {@code >} characters in {@code value} will be escaped.
     *
     * @param  element The HTML element without brackets (e.g. {@code "h1"}).
     * @param  value The text to write, or {@code null} for none.
     * @throws IOException if an error occurred while writing to the file.
     */
    protected final void println(final String element, final CharSequence value) throws IOException {
        printlnHTML(element, escape(value));
    }

    /**
     * Writes the given text in the given HTML element without escaping the characters.
     * This method can be invoked when the given {@code value} is already valid HTML
     *
     * @param  element The HTML element without brackets (e.g. {@code "h1"}).
     * @param  value The text to write, or {@code null} for none.
     * @throws IOException if an error occurred while writing to the file.
     */
    protected final void printlnHTML(final String element, final CharSequence value) throws IOException {
        out.write(margin);
        out.write('<');
        out.write(element);
        out.write('>');
        if (value != null) {
            out.write(value.toString());
        }
        out.write("</");
        final int s = element.indexOf(' ');
        out.write(element, 0, (s >= 0) ? s : element.length());
        out.write('>');
        out.newLine();
    }

    /**
     * Writes the given text on its own line, then write EOL sequence.
     * {@code &}, {@code <} and {@code >} characters in {@code value} will be escaped.
     *
     * @param  value The text to write, or {@code null} if none.
     * @throws IOException if an error occurred while writing to the file.
     */
    protected final void println(final CharSequence value) throws IOException {
        if (value != null) {
            out.write(margin);
            out.write(escape(value).toString());
            out.newLine();
        }
    }

    /**
     * Closes the HTML generator.
     *
     * @throws IOException if an error occurred while closing the output file.
     */
    @Override
    public void close() throws IOException {
        close("body");
        close("html");
        out.close();
    }

    /**
     * Returns the localized version of the given string, or {@code null} if none.
     *
     * @param  text The text to localize, or {@code null}.
     * @return The localized test, or {@code null}.
     *
     * @see #LOCALE
     */
    protected static String toLocalizedString(final InternationalString text) {
        return (text != null) ? text.toString(LOCALE) : null;
    }

    /**
     * Returns {@code true} if the given object is deprecated.
     *
     * @param  object The object to test.
     * @return {@code true} if the given object is deprecated.
     */
    protected static boolean isDeprecated(final Object object) {
        return (object instanceof Deprecable) && ((Deprecable) object).isDeprecated();
    }
}
